INSERT INTO JOB(ID, NAME, ACTIVE) VALUES (1,'JOB 01', TRUE);
INSERT INTO JOB(ID, NAME, ACTIVE) VALUES (2,'JOB 02', FALSE);
INSERT INTO JOB(ID, NAME, ACTIVE) VALUES (3,'JOB 03', TRUE);
INSERT INTO JOB(ID, NAME, ACTIVE) VALUES (4,'JOB 04', FALSE);
INSERT INTO JOB(ID, NAME, ACTIVE) VALUES (5,'JOB 05', TRUE);

INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (1, 1, 2);
INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (2, 1, 3);
INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (3, 1, 3);
INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (4, 2, 4);
INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (5, 3, 2);
INSERT INTO PARENT_JOB(ID, IDJOBPRIMARY, IDJOBSECUNDARY) VALUES (6, 3, 5);

INSERT INTO TASK(ID, NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES (1,'TASK 01', 12, TRUE, SYSDATE);
INSERT INTO TASK(ID, NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES (2,'TASK 02', 10, FALSE, SYSDATE);
INSERT INTO TASK(ID, NAME, WEIGHT, COMPLETED, CREATED_AT) VALUES (3,'TASK 03', 13, TRUE, SYSDATE);